name: Bug Report
description: Report a bug in VibeyMapTools
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: tool
    attributes:
      label: Which tool?
      description: Which VibeyMapTools component is affected?
      options:
        - vmt-bsp
        - vmt-vis
        - vmt-light
        - vmt-bspinfo
        - vmt-bsputil
        - maputil
        - lightpreview
        - Other/Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With map file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: system
    attributes:
      label: Environment
      description: Please provide your system info
      placeholder: |
        - OS: Windows 11 / Ubuntu 22.04 / macOS 14
        - VibeyMapTools version: 2.1.0
        - Target game: Quake / Quake 2 / etc.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Paste any relevant log output or error messages
      render: shell

  - type: textarea
    id: map
    attributes:
      label: Sample Map File
      description: If possible, attach or link a minimal .map file that reproduces the issue
