name: Feature Request
description: Suggest a new feature for VibeyMapTools
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: dropdown
    id: tool
    attributes:
      label: Which tool?
      description: Which tool would this feature apply to?
      options:
        - vmt-bsp
        - vmt-vis
        - vmt-light
        - vmt-bspinfo
        - vmt-bsputil
        - maputil
        - lightpreview
        - All tools
        - New tool
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of what you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this solve? What's your use case?
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
