function(vmt_resolve_version SOURCE_DIR)
	if(NOT SOURCE_DIR)
		set(SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
	endif()

	set(VMT_VERSION_FILE "0.0.0")
	if(EXISTS "${SOURCE_DIR}/VERSION")
		file(READ "${SOURCE_DIR}/VERSION" VMT_VERSION_FILE_RAW)
		string(STRIP "${VMT_VERSION_FILE_RAW}" VMT_VERSION_FILE)
	endif()

	set(VMT_GIT_DESCRIBE "")
	set(VMT_GIT_DESCRIBE_CLEAN "")
	set(VMT_GIT_TAG "")
	set(VMT_GIT_COMMITS "")
	set(VMT_GIT_SHA "")
	set(VMT_GIT_DIRTY FALSE)

	find_package(Git QUIET)
	if(GIT_FOUND AND EXISTS "${SOURCE_DIR}/.git")
		execute_process(
			COMMAND "${GIT_EXECUTABLE}" describe --tags --match "v[0-9]*" --abbrev=8 --dirty
			WORKING_DIRECTORY "${SOURCE_DIR}"
			RESULT_VARIABLE VMT_GIT_DESCRIBE_RESULT
			OUTPUT_VARIABLE VMT_GIT_DESCRIBE
			OUTPUT_STRIP_TRAILING_WHITESPACE
		)
		if(NOT VMT_GIT_DESCRIBE_RESULT EQUAL 0)
			set(VMT_GIT_DESCRIBE "")
		endif()

		execute_process(
			COMMAND "${GIT_EXECUTABLE}" rev-parse --short=8 HEAD
			WORKING_DIRECTORY "${SOURCE_DIR}"
			RESULT_VARIABLE VMT_GIT_SHA_RESULT
			OUTPUT_VARIABLE VMT_GIT_SHA
			OUTPUT_STRIP_TRAILING_WHITESPACE
		)
		if(NOT VMT_GIT_SHA_RESULT EQUAL 0)
			set(VMT_GIT_SHA "")
		endif()
	endif()

	if(VMT_GIT_DESCRIBE MATCHES "-dirty$")
		set(VMT_GIT_DIRTY TRUE)
		string(REGEX REPLACE "-dirty$" "" VMT_GIT_DESCRIBE_CLEAN "${VMT_GIT_DESCRIBE}")
	else()
		set(VMT_GIT_DESCRIBE_CLEAN "${VMT_GIT_DESCRIBE}")
	endif()

	if(VMT_GIT_DESCRIBE_CLEAN MATCHES "^v([^\\s]+)-([0-9]+)-g([0-9a-f]+)$")
		set(VMT_GIT_TAG "${CMAKE_MATCH_1}")
		set(VMT_GIT_COMMITS "${CMAKE_MATCH_2}")
		set(VMT_GIT_SHA "${CMAKE_MATCH_3}")
	elseif(VMT_GIT_DESCRIBE_CLEAN MATCHES "^v([^\\s]+)$")
		set(VMT_GIT_TAG "${CMAKE_MATCH_1}")
	endif()

	set(VMT_VERSION_BASE "${VMT_VERSION_FILE}")
	if(VMT_GIT_TAG)
		set(VMT_VERSION_BASE "${VMT_GIT_TAG}")
	elseif(DEFINED ENV{GITHUB_REF_NAME} AND "$ENV{GITHUB_REF_NAME}" MATCHES "^v(.+)$")
		set(VMT_VERSION_BASE "${CMAKE_MATCH_1}")
	endif()

	set(VMT_VERSION_FULL "${VMT_VERSION_BASE}")
	if(VMT_GIT_COMMITS)
		set(VMT_VERSION_FULL "${VMT_VERSION_BASE}-dev.${VMT_GIT_COMMITS}")
		if(VMT_GIT_SHA)
			set(VMT_VERSION_FULL "${VMT_VERSION_FULL}+g${VMT_GIT_SHA}")
		endif()
	elseif(VMT_GIT_DIRTY)
		set(VMT_VERSION_FULL "${VMT_VERSION_BASE}+dirty")
	elseif(NOT VMT_GIT_DESCRIBE AND DEFINED ENV{GITHUB_SHA})
		string(SUBSTRING "$ENV{GITHUB_SHA}" 0 8 VMT_ENV_SHA)
		set(VMT_GIT_SHA "${VMT_ENV_SHA}")
		set(VMT_VERSION_FULL "${VMT_VERSION_BASE}-dev+g${VMT_ENV_SHA}")
	endif()

	set(VMT_VERSION_PACKAGE "${VMT_VERSION_FULL}")
	string(REPLACE "+" "-" VMT_VERSION_PACKAGE "${VMT_VERSION_PACKAGE}")

	set(VMT_VERSION_GIT_LABEL "${VMT_GIT_DESCRIBE}")
	if(NOT VMT_VERSION_GIT_LABEL AND VMT_GIT_SHA)
		set(VMT_VERSION_GIT_LABEL "g${VMT_GIT_SHA}")
	endif()

	string(REPLACE "-" ";" VMT_VERSION_PARTS "${VMT_VERSION_BASE}")
	list(GET VMT_VERSION_PARTS 0 VMT_VERSION_NUMERIC)
	string(REPLACE "." ";" VMT_VERSION_NUM_PARTS "${VMT_VERSION_NUMERIC}")
	list(LENGTH VMT_VERSION_NUM_PARTS VMT_VERSION_NUM_PARTS_LEN)
	if(VMT_VERSION_NUM_PARTS_LEN LESS 3)
		message(FATAL_ERROR "VERSION must be MAJOR.MINOR.PATCH (got '${VMT_VERSION_BASE}')")
	endif()
	list(GET VMT_VERSION_NUM_PARTS 0 VMT_VERSION_MAJOR)
	list(GET VMT_VERSION_NUM_PARTS 1 VMT_VERSION_MINOR)
	list(GET VMT_VERSION_NUM_PARTS 2 VMT_VERSION_PATCH)

	set(VIBEY_VERSION_STRING "${VMT_VERSION_BASE}" PARENT_SCOPE)
	set(VIBEY_VERSION_FULL "${VMT_VERSION_FULL}" PARENT_SCOPE)
	set(VIBEY_VERSION_GIT "${VMT_VERSION_GIT_LABEL}" PARENT_SCOPE)
	set(VIBEY_VERSION_MAJOR "${VMT_VERSION_MAJOR}" PARENT_SCOPE)
	set(VIBEY_VERSION_MINOR "${VMT_VERSION_MINOR}" PARENT_SCOPE)
	set(VIBEY_VERSION_PATCH "${VMT_VERSION_PATCH}" PARENT_SCOPE)
	set(VIBEY_VERSION_PACKAGE "${VMT_VERSION_PACKAGE}" PARENT_SCOPE)
	set(VIBEY_VERSION_NUMERIC "${VMT_VERSION_NUMERIC}" PARENT_SCOPE)
endfunction()
